package com.marcoscornejos.sales_management_system.projection;

import java.math.BigDecimal;

/**
 * Projection interface used to retrieve product sales statistics
 * directly from database queries.
 *
 * <p>
 * It provides aggregated product performance data such as
 * quantity sold and revenue generated within a given filter range.
 * </p>
 */
public interface SoldProductProjection {

    /**
     * Unique product code that identifies the product.
     */
    String getProductCode();

    /**
     * Name of the product.
     */
    String getProductName();

    /**
     * Total quantity of units sold for this product
     * within the selected range.
     */
    BigDecimal getQuantitySold();

    /**
     * Total revenue generated by this product
     * within the selected range.
     */
    BigDecimal getRevenueGenerated();
}
