package com.marcoscornejos.sales_management_system.projection;

import java.math.BigDecimal;

/**
 * Projection interface used to retrieve top-performing products
 * ranked by revenue generated.
 *
 * <p>
 * Provides only the fields required for revenue-based
 * product ranking charts.
 * </p>
 */
public interface TopProductsByRevenueProjection {

    /**
     * Unique product code that identifies the product.
     *
     * @return product code
     */
    String getProductCode();

    /**
     * Name of the product.
     *
     * @return product name
     */
    String getProductName();

    /**
     * Total revenue generated by this product
     * within the selected range.
     *
     * @return revenue generated
     */
    BigDecimal getRevenueGenerated();
}