/**
 * Repository interface for managing {@link Sale} entities.
 *
 * <p>
 * Extends {@link JpaRepository}, providing standard CRUD operations
 * such as save, delete, findById, and findAll without requiring
 * explicit implementation.
 * </p>
 *
 * <p>
 * This repository handles data access for sales.
 * Custom query methods can be defined here when needed.
 * </p>
 */

package com.marcoscornejos.sales_management_system.repository;

import com.marcoscornejos.sales_management_system.model.Sale;
import com.marcoscornejos.sales_management_system.model.User;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.EntityGraph;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import com.marcoscornejos.sales_management_system.projection.TimeSeriesProjection;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;

@Repository
public interface ISaleRepository extends JpaRepository<Sale, Long> {

    /**
     * Retrieves sales with optional search by sale identifier,
     * filtered by sale date, applying pagination and sorting
     * at the database level.
     *
     * <p>
     * Search is applied on exact match of sale identifier.
     * If {@code searchSaleId} is null, search is ignored.
     * </p>
     *
     * <p>
     * Sales are always filtered by exact match on sale date.
     * </p>
     *
     * <p>
     * Pagination and sorting are handled using {@link Pageable},
     * ensuring efficient server-side data retrieval.
     * </p>
     *
     * <p>
     * The associated user is loaded using {@link EntityGraph}
     * to avoid N+1 query problems.
     * </p>
     *
     * @param searchSaleId optional sale identifier
     * @param date sale date filter
     * @param pageable pagination and sorting configuration
     * @return paginated result of matching sales
     */
    @EntityGraph(attributePaths = "user")
    @Query("""
    SELECT s FROM Sale s
    WHERE
        (
            :searchSaleId IS NULL OR
            s.saleId = :searchSaleId
        )
    AND
        s.saleDate = :date
    """)
    Page<Sale> findSales(Long searchSaleId,
                         LocalDate date,
                         Pageable pageable);

    /**
     * Retrieves a sale with its details, products, and user.
     *
     * <p>
     * Uses JOIN FETCH to load associated entities and avoid additional queries
     * caused by lazy loading.
     * </p>
     *
     * @param saleId the unique identifier of the sale
     * @return an Optional containing the sale with its details, products, and user
     */
    @Query("""
        SELECT DISTINCT s FROM Sale s
        JOIN FETCH s.saleDetails sd
        JOIN FETCH sd.product
        JOIN FETCH s.user
        WHERE s.saleId = :saleId
    """)
    Optional<Sale> findByIdWithDetailsAndProducts(Long saleId);


    /**
     * Retrieves a sale with its details for ticket generation.
     *
     * <p>
     * Loads the sale and its associated sale details in a single query.
     * Product and user entities are not fetched because the ticket uses
     * historical snapshot data stored in SaleDetail.
     * </p>
     *
     * @param saleId the unique identifier of the sale
     * @return an Optional containing the sale with its details
     */
    @Query("""
    SELECT DISTINCT s FROM Sale s
    JOIN FETCH s.saleDetails sd
    WHERE s.saleId = :saleId
    """)
    Optional<Sale> findByIdWithDetails(Long saleId);

    /**
     * Calculates the total revenue generated by sales
     * within the provided filters.
     *
     * <p>
     * Revenue is calculated as the sum of all sale total amounts.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * If no matching sales exist, returns {@link BigDecimal#ZERO}.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return total revenue for matching sales
     */
    @Query("""
    SELECT COALESCE(SUM(s.totalAmount), 0)
    FROM Sale s
    WHERE
        (
            :userId IS NULL OR
            s.user.userId = :userId
        )
    AND
        s.saleDate BETWEEN :startDate AND :endDate
    """)
    BigDecimal sumRevenue(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Counts the number of sales that match the provided filters.
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * The result represents the total number of sale records
     * within the selected date range.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return total number of matching sales
     */
    @Query("""
    SELECT COUNT(s.saleId)
    FROM Sale s
    WHERE (:userId IS NULL OR s.user.userId = :userId)
    AND s.saleDate BETWEEN :startDate AND :endDate
    """)
    Long countSales(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves the hour of the day (0–23) with the highest generated revenue
     * within the provided filters.
     *
     * <p>
     * Sales are grouped by hour and ranked
     * by total generated revenue.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return hour (0–23) with the highest revenue,
     *         or null if no matching sales exist
     */
    @Query(value = """
    SELECT
        EXTRACT(HOUR FROM s.sale_time) AS hour
    FROM core.sale s
    WHERE
        (
            :userId IS NULL
            OR s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY EXTRACT(HOUR FROM s.sale_time)
    ORDER BY SUM(s.total_amount) DESC
    LIMIT 1
    """, nativeQuery = true)
    Integer findPeakRevenueHour(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves the hour of the day (0–23) with the highest number of sales
     * within the provided filters.
     *
     * <p>
     * Sales are grouped by hour and ranked
     * by total number of sales records.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return hour (0–23) with the highest number of sales,
     *         or null if no matching sales exist
     */
    @Query(value = """
    SELECT
        EXTRACT(HOUR FROM s.sale_time) AS hour
    FROM core.sale s
    WHERE
        (
            :userId IS NULL
            OR s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY EXTRACT(HOUR FROM s.sale_time)
    ORDER BY COUNT(s.sale_id) DESC
    LIMIT 1
    """, nativeQuery = true)
    Integer findPeakSalesHour(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves revenue aggregated by hour for chart visualization.
     *
     * <p>
     * Revenue is calculated as the sum of sale total amounts
     * grouped by sale hour.
     * </p>
     *
     * <p>
     * This aggregation is used for single-day date ranges
     * to provide more detailed chart visualization.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * Results are ordered chronologically by hour.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return hourly revenue time series
     */
    @Query(value = """
    SELECT
        TO_CHAR(s.sale_time, 'HH24') AS label,
        COALESCE(SUM(s.total_amount), 0) AS value
    FROM core.sale s
    WHERE
        (
            :userId IS NULL OR
            s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY TO_CHAR(s.sale_time, 'HH24')
    ORDER BY TO_CHAR(s.sale_time, 'HH24')
    """, nativeQuery = true)
    List<TimeSeriesProjection> getRevenuePerHour(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves revenue aggregated by day for chart visualization.
     *
     * <p>
     * Revenue is calculated as the sum of sale total amounts
     * grouped by sale date.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * Results are ordered chronologically.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return daily revenue time series
     */
    @Query(value = """
    SELECT
        TO_CHAR(s.sale_date, 'YYYY-MM-DD') AS label,
        COALESCE(SUM(s.total_amount), 0) AS value
    FROM core.sale s
    WHERE
        (
            :userId IS NULL OR
            s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY s.sale_date
    ORDER BY s.sale_date
    """, nativeQuery = true)
    List<TimeSeriesProjection> getRevenuePerDay(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves revenue aggregated by month for chart visualization.
     *
     * <p>
     * Revenue is calculated as the sum of sale total amounts
     * grouped by month and year.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * Results are ordered chronologically.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return monthly revenue time series
     */
    @Query(value = """
    SELECT
        TO_CHAR(s.sale_date, 'YYYY-MM') AS label,
        COALESCE(SUM(s.total_amount), 0) AS value
    FROM core.sale s
    WHERE
        (
            :userId IS NULL OR
            s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY TO_CHAR(s.sale_date, 'YYYY-MM')
    ORDER BY TO_CHAR(s.sale_date, 'YYYY-MM')
    """, nativeQuery = true)
    List<TimeSeriesProjection> getRevenuePerMonth(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves revenue aggregated by year for chart visualization.
     *
     * <p>
     * Revenue is calculated as the sum of sale total amounts
     * grouped by year.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * Results are ordered chronologically.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return yearly revenue time series
     */
    @Query(value = """
    SELECT
        TO_CHAR(s.sale_date, 'YYYY') AS label,
        COALESCE(SUM(s.total_amount), 0) AS value
    FROM core.sale s
    WHERE
        (
            :userId IS NULL OR
            s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY TO_CHAR(s.sale_date, 'YYYY')
    ORDER BY TO_CHAR(s.sale_date, 'YYYY')
    """, nativeQuery = true)
    List<TimeSeriesProjection> getRevenuePerYear(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves sales count aggregated by hour for chart visualization.
     *
     * <p>
     * Sales count is calculated as the total number of sale records
     * grouped by sale hour.
     * </p>
     *
     * <p>
     * This aggregation is used for single-day date ranges
     * to provide more detailed chart visualization.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * Results are ordered chronologically by hour.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return hourly sales count time series
     */
    @Query(value = """
    SELECT
        TO_CHAR(s.sale_time, 'HH24') AS label,
        CAST(COUNT(s.sale_id) AS NUMERIC) AS value
    FROM core.sale s
    WHERE
        (
            :userId IS NULL OR
            s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY TO_CHAR(s.sale_time, 'HH24')
    ORDER BY TO_CHAR(s.sale_time, 'HH24')
    """, nativeQuery = true)
    List<TimeSeriesProjection> getSalesPerHour(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves sales count aggregated by day for chart visualization.
     *
     * <p>
     * Sales count is calculated as the total number of sale records
     * grouped by sale date.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * Results are ordered chronologically.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return daily sales count time series
     */
    @Query(value = """
    SELECT
        TO_CHAR(s.sale_date, 'YYYY-MM-DD') AS label,
        CAST(COUNT(s.sale_id) AS NUMERIC) AS value
    FROM core.sale s
    WHERE
        (
            :userId IS NULL OR
            s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY s.sale_date
    ORDER BY s.sale_date
    """, nativeQuery = true)
    List<TimeSeriesProjection> getSalesPerDay(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves sales count aggregated by month for chart visualization.
     *
     * <p>
     * Sales count is calculated as the total number of sale records
     * grouped by month and year.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * Results are ordered chronologically.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return monthly sales count time series
     */
    @Query(value = """
    SELECT
        TO_CHAR(s.sale_date, 'YYYY-MM') AS label,
        CAST(COUNT(s.sale_id) AS NUMERIC) AS value
    FROM core.sale s
    WHERE
        (
            :userId IS NULL OR
            s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY TO_CHAR(s.sale_date, 'YYYY-MM')
    ORDER BY TO_CHAR(s.sale_date, 'YYYY-MM')
    """, nativeQuery = true)
    List<TimeSeriesProjection> getSalesPerMonth(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );

    /**
     * Retrieves sales count aggregated by year for chart visualization.
     *
     * <p>
     * Sales count is calculated as the total number of sale records
     * grouped by year.
     * </p>
     *
     * <p>
     * If {@code userId} is null, sales from all users are included.
     * </p>
     *
     * <p>
     * Results are ordered chronologically.
     * </p>
     *
     * @param userId optional user filter (null = all users)
     * @param startDate start date filter
     * @param endDate end date filter
     * @return yearly sales count time series
     */
    @Query(value = """
    SELECT
        TO_CHAR(s.sale_date, 'YYYY') AS label,
        CAST(COUNT(s.sale_id) AS NUMERIC) AS value
    FROM core.sale s
    WHERE
        (
            :userId IS NULL OR
            s.user_id = :userId
        )
    AND
        s.sale_date BETWEEN :startDate AND :endDate
    GROUP BY TO_CHAR(s.sale_date, 'YYYY')
    ORDER BY TO_CHAR(s.sale_date, 'YYYY')
    """, nativeQuery = true)
    List<TimeSeriesProjection> getSalesPerYear(
            Long userId,
            LocalDate startDate,
            LocalDate endDate
    );
}
