package com.marcoscornejos.sales_management_system.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Represents a product with associated sales performance metrics.
 *
 * <p>
 * This DTO is used in product ranking and top-product analytics,
 * containing both identity information and performance indicators such as
 * quantity sold and revenue generated within the selected filter range.
 * </p>
 */

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class SoldProductDTO {

    /**
     * Unique product code that identifies the product.
     */
    private String productCode;

    /**
     * Name of the product.
     */
    private String productName;

    /**
     * Total quantity of units sold for this product in the selected range.
     */
    private BigDecimal quantitySold;

    /**
     * Total revenue generated by this product in the selected range.
     */
    private BigDecimal revenueGenerated;
}
