package com.marcoscornejos.sales_management_system.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Represents a top-performing product ranked by revenue generated.
 *
 * <p>
 * This DTO is used for chart visualizations that display
 * the products that generated the highest revenue
 * within the selected filter range.
 * </p>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class TopProductsByRevenueDTO {

    /**
     * Unique product code that identifies the product.
     */
    private String productCode;

    /**
     * Name of the product.
     */
    private String productName;

    /**
     * Total revenue generated by this product
     * within the selected range.
     */
    private BigDecimal revenueGenerated;
}